### ISSUE TITLE
Fluxgym won't start

### ISSUE THREAD

**Issue by palvarez19** [cocktailpeanut/fluxgym#112]
Getting the following error with a fresh install (code as of 19 Sept):

Traceback (most recent call last):
  File "app.py", line 19, in <module>
    from library import flux_train_utils, huggingface_util
  File "/home/test/fluxgym/sd-scripts/library/flux_train_utils.py", line 17, in <module>
    from library import flux_models, flux_utils, strategy_base, train_util
  File "/home/test/fluxgym/sd-scripts/library/flux_models.py", line 22, in <module>
    class FluxParams:
  File "/home/test/fluxgym/sd-scripts/library/flux_models.py", line 31, in FluxParams
    axes_dim: list[int]
TypeError: 'type' object is not subscriptable

**Comment by 6Morpheus6** [comment]
@palvarez19
Do you get it when you try to start Flux?
I installed it as well a few hours ago. It was starting on Windows 10.
Also please check if the unet model is present in `./fluxgym/models/unet`
the 2 clip models are in `./fluxgym/models/clip`
and the vae model is in `./fluxgym/models/vae`

**Comment by palvarez19** [comment]
> @palvarez19 Do you get it when you try to start Flux? I installed it as well a few hours ago. It was starting on Windows 10. Also please check if the unet model is present in `./fluxgym/models/unet` the 2 clip models are in `./fluxgym/models/clip` and the vae model is in `./fluxgym/models/vae`

Yes, I doubled checked and all the files are in the right directories.

**Comment by palvarez19** [comment]
I reinstalled everything again, but specifying python3.10, like this: python3.10 -m venv env. Fluxgym ran after doing that.
