### ISSUE TITLE
enable buckets

### ISSUE THREAD

**Issue by zethfoxster** [cocktailpeanut/fluxgym#119]
enable buckets is set to false in the script, can we please get a checkbox option for this.

**Comment by gohan2091** [comment]
All my images are different ratios and dimensions. Do I need to have buckets enabled? the default is off but didn't have a problem when I tried creating a LoRA a few weeks ago.

**Comment by zethfoxster** [comment]
its cropping the images if you dont enable buckets and have a mix...which sometimes can end up cropping off faces, or key items in the images....this issue can be closed as he since added a method to edit that directly in the webui on the right side, you can just edit it to true.
