### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by deepfree2023** [cocktailpeanut/fluxgym#133]
Encounted 2 errors：
1. Fluxgym cannot create outputs/xxx/sample directory, and report dir not exist error
2. After I manually created the dir, Fluxgym report the following error:

  File "K:\ComfyUI_windows_portable\fluxgym\app.py", line 625, in start_training
    md = readme(base_model, lora_name, concept_sentence, sample_prompts)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\fluxgym\app.py", line 73, in readme
    _, _, image_path = final_sample_image_paths[i]
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Shavalyoth** [comment]
I've experienced the same error.

**Comment by deepfree2023** [comment]
Got it. My accelerate.exe was not the the system path.

**Comment by wmbassyouni** [comment]
Hi @deepfree2023 can you please provide the exact steps you took to fix it ? I have the same issue.

**Comment by mertayd0** [comment]
> Hi @deepfree2023 can you please provide the exact steps you took to fix it ? I have the same issue.

+1

**Comment by Friedrish933** [comment]
+1

**Comment by deepfree2023** [comment]
Hi, I just added my accelerate.exe path into the system path, and it worked. But not working efficiently, no partially loading into vram, the training speed was very very slow.
