### ISSUE TITLE
Dockerfile has a capital f

### ISSUE THREAD

**Issue by sbrown345** [cocktailpeanut/fluxgym#139]
The Dockerfile has a capital 'f': "DockerFile"

I got this error on Linux:
```
docker compose up -d --build
[+] Building 0.2s (1/1) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 2B                                         0.0s
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

This fixed it:
```sh
mv DockerFile Dockerfile
```

**Comment by cocktailpeanut** [comment]
@fahadshery is this still relevant?

**Comment by fahadshery** [comment]
> @fahadshery is this still relevant?

yes, I tried renaming it in the previous commit but for some reason it won't let me upload/update here. Could you do it please?

PS I am `Dockerfile` on my local system

**Comment by sbrown345** [comment]
This might work: `git mv --force DockerFile Dockerfile`

**Comment by cocktailpeanut** [comment]
Done https://github.com/cocktailpeanut/fluxgym/commit/5ca0afbdf0577ad8e92cd7df006fb3f4b9574c72
