### ISSUE TITLE
AssertionError: caption file is empty

### ISSUE THREAD

**Issue by ILikeToasters** [cocktailpeanut/fluxgym#144]
Getting an error when I start training. I manually create my own caption files and add them with the images. Seems to have worked fine until today after adding some more detail to the captions. I do notice that once it starts that one of the txt files in the dataset folder will have an empty file. But all images do have captions when I start and the original txt files also have the captions. 

[ui log.txt](https://github.com/user-attachments/files/17176997/ui.log.txt)
[terminal log.txt](https://github.com/user-attachments/files/17176998/terminal.log.txt)

**Comment by cocktailpeanut** [comment]
@ILikeToasters  just pushed a commit that should fix it https://github.com/cocktailpeanut/fluxgym/commit/e654984863be30d797ed88cfdbddf12a75e4c589 can you try and report how it goes

**Comment by ILikeToasters** [comment]
> @ILikeToasters just pushed a commit that should fix it [e654984](https://github.com/cocktailpeanut/fluxgym/commit/e654984863be30d797ed88cfdbddf12a75e4c589) can you try and report how it goes

Just updated and gave it a try and seems to be working. Thanks!
