### ISSUE TITLE
[Feature request] Server Port argument

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [cocktailpeanut/fluxgym#149]
I found and read the #80 post, and I've gotten it to work on a custom port.

It seems like it would be a nice launch argument to add to the script, as a user-friendly way to not require people to set environment variables.

Using an environment variable doesn't make sense to me since this will not be the only gradio app I'm running, which is the reason why I'm looking to change the port.

I made it working like this:
```
app.py:
if __name__ == "__main__":
    cwd = os.path.dirname(os.path.abspath(__file__))
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 7860  # Default to 7860 if no port is provided
    demo.launch(debug=True, show_error=True, allowed_paths=[cwd], server_port=port)


In my launch.bat:
@echo off 
set PORT=7861
call venv\Scripts\activate
cmd /k "cd /d %~dp0 & call venv\Scripts\activate & python app.py %PORT%"
```

Just in case this helps anyone else.

But I still would love to just be able to set this in a user config so I wouldn't need to update project source files.

**Comment by Semonxue** [comment]
try this:
```
//linux or mac
export GRADIO_SERVER_PORT=5000
or
//windows in cmd
set GRADIO_SERVER_PORT=5000
```
then run the app

**Comment by MNeMoNiCuZ** [comment]
> try this:
> 
> ```
> //linux or mac
> export GRADIO_SERVER_PORT=5000
> or
> //windows in cmd
> set GRADIO_SERVER_PORT=5000
> ```
> 
> then run the app

Thanks for the tip.
But as mentioned in my post, I don't really want to set gradio server ports as I have other gradio apps running.
I just want to be able to customize the instance of this program in a friendly way, without modifying the original code.
