### ISSUE TITLE
torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.

### ISSUE THREAD

**Issue by Iamausername1958** [cocktailpeanut/fluxgym#156]
Was working fine yesterday. Now I can't seem to make it work

\checkpoint.py:1399: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.

**Comment by restofworld** [comment]
same problem

**Comment by Iamausername1958** [comment]
Found another thread with that same problem. This was cocktailpeanut's answer: 


"I think this is a warning and not an error. Unless the process crashes it is still going.

Even I see this warning message but the training works fine. The reason it is not updating quickly is because the script seems to only print all the updates after each epoch (instead of each step).

This means it takes quite some time before the first progress is printed on the screen. So unless the program completely crashes and you don't see any VRAM usage on your task manager, try to keep it running and see if it updates."


Will run it overnight and update tomorrow as my GPU is indeed working in the back end! I wonder why it just stopped showing steps all of the sudden though.

**Comment by baobao1712** [comment]
just let it run and it will progress to the next step, I fixed the code and it still running like this so it doesn't matter.

**Comment by Iamausername1958** [comment]
I can confirm that it does work! Ignore the warning if it doesn't crash. 

Thanks everyone!
