### ISSUE TITLE
Install FluxGym on an AMD gpu

### ISSUE THREAD

**Issue by ornelasnarciso** [cocktailpeanut/fluxgym#252]
Hello. Need help.

Followed this tutorial to install FluxGym on my nvidia card: [](https://comfyuiweb.com/posts/flux-gym-low-vram-training) It works just fine on my ubuntu 24.04 machine. 

My issue is with my AMD gpu, the same steps don't work. The service launches but does not use the GPU. Is there any tutorial on how I should install FLxGym correctly and make it run with my AMD gpu? 

Thank you.

**Comment by ornelasnarciso** [comment]
> AMD GPU require [pytorch ROCm version , and ROCm](https://pytorch.org/get-started/locally/) by run `source env/bin/activate` `pip install torch...`

Thank you but I have no idea what to do with that information.

**Comment by likelovewant** [comment]
> > AMD GPU require [pytorch ROCm version , and ROCm](https://pytorch.org/get-started/locally/) by run `source env/bin/activate` `pip install torch...`
> 
> 
> 
> Thank you but I have no idea what to do with that information.

Simply install as the guide in the readme . Then do extra steps.
Activate the the python environment:

`source env/bin/activate`

Then install PyTorch by run:

'pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2'

Now,it's done for the fluxgym 

However, need install rocm for your system in Linux.simply google it . 

If your AMD Gpu not supported by ROCm, 

You may need run ' expo HSA_OVERRIDE_GFX_VERSION=10.3.0' something like this in your script to fake your gpu as gfx1030 . Changes this to others if your arches are others than gfx10xx series. Then launch the script. Google something like " how to use stable diffusion in Linux for AMD gpu " similar issue would help you get the points why doing this . 

@

**Comment by ornelasnarciso** [comment]
I was able to install but when I it run if fails like it did with my nvidia gpu. To much trouble to run fluxgym. Thanks anyway.

**Comment by goffy76** [comment]
I got i running like this: cd fluxgym && source env/bin/activate && export HSA_OVERRIDE_GFX_VERSION=11.0.0  && python3 app.py  on my 7800XT, but it uses the CPU, not the GPU. Any ideas?

**Comment by likelovewant** [comment]
> I got i running like this: cd fluxgym && source env/bin/activate && export HSA_OVERRIDE_GFX_VERSION=11.0.0  && python3 app.py  on my 7800XT, but it uses the CPU, not the GPU. Any ideas?


The only difference between Nvida and AMD is the PyTorch version . So you need install PyTorch rocm. And use your set . And try to select , 16g instead of 20g as it will require AdamW optimizer which may not support . If there is any other reason stop to use gpu . The console log will help you debug it .The rule is same as stable diffusion. 
@goffy76

**Comment by sebinator** [comment]
> I got i running like this: cd fluxgym && source env/bin/activate && export HSA_OVERRIDE_GFX_VERSION=11.0.0 && python3 app.py on my 7800XT, but it uses the CPU, not the GPU. Any ideas?

Did you managed to make this work? I also have a 7800XT

But when i am launching the app, i get this : 

(env) G:\A.I\fluxgym>python app.py
2025-01-21 09:18:38 WARNING  The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU            cextension.py:96
                             quantization are unavailable.


So flyxgym is using cpu instead of gpu

**Comment by sebinator** [comment]
> > I got i running like this: cd fluxgym && source env/bin/activate && export HSA_OVERRIDE_GFX_VERSION=11.0.0  && python3 app.py  on my 7800XT, but it uses the CPU, not the GPU. Any ideas?
> 
> The only difference between Nvida and AMD is the PyTorch version . So you need install PyTorch rocm. And use your set . And try to select , 16g instead of 20g as it will require AdamW optimizer which may not support . If there is any other reason stop to use gpu . The console log will help you debug it .The rule is same as stable diffusion. [@goffy76](https://github.com/goffy76)

I have the same issue, 
i tried : >pip install torch

and it seems to install  : 

(env) G:\A.I\fluxgym>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2'
Looking in indexes: https://download.pytorch.org/whl/rocm6.2'
Requirement already satisfied: torch in g:\a.i\fluxgym\env\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: torchvision in g:\a.i\fluxgym\env\lib\site-packages (0.20.1)
Requirement already satisfied: torchaudio in g:\a.i\fluxgym\env\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: sympy==1.13.1 in g:\a.i\fluxgym\env\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: networkx in g:\a.i\fluxgym\env\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: fsspec in g:\a.i\fluxgym\env\lib\site-packages (from torch) (2024.12.0)
Requirement already satisfied: filelock in g:\a.i\fluxgym\env\lib\site-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in g:\a.i\fluxgym\env\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: jinja2 in g:\a.i\fluxgym\env\lib\site-packages (from torch) (3.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in g:\a.i\fluxgym\env\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in g:\a.i\fluxgym\env\lib\site-packages (from torchvision) (10.4.0)
Requirement already satisfied: numpy in g:\a.i\fluxgym\env\lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: MarkupSafe>=2.0 in g:\a.i\fluxgym\env\lib\site-packages (from jinja2->torch) (2.1.5)


But i keep having the following message when launching fluxgym : 
(env) G:\A.I\fluxgym>python app.py
2025-01-21 09:18:38 WARNING The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU cextension.py:96
quantization are unavailable.

**Comment by goffy76** [comment]
> > I got i running like this: cd fluxgym && source env/bin/activate && export HSA_OVERRIDE_GFX_VERSION=11.0.0 && python3 app.py on my 7800XT, but it uses the CPU, not the GPU. Any ideas?
> 
> Did you managed to make this work? I also have a 7800XT
> 
> But when i am launching the app, i get this :
> 
> (env) G:\A.I\fluxgym>python app.py 2025-01-21 09:18:38 WARNING The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU cextension.py:96 quantization are unavailable.
> 
> So flyxgym is using cpu instead of gpu

No, I gave up. I'm not good enough with this Kode twerking to know how to fix it.
I rent a 4090 on vast.ai instead. It's about 0,4 USD an hour and then you can use your pc for other tasks while it's running 😊

**Comment by sebinator** [comment]
> > > I got i running like this: cd fluxgym && source env/bin/activate && export HSA_OVERRIDE_GFX_VERSION=11.0.0 && python3 app.py on my 7800XT, but it uses the CPU, not the GPU. Any ideas?
> > 
> > 
> > Did you managed to make this work? I also have a 7800XT
> > But when i am launching the app, i get this :
> > (env) G:\A.I\fluxgym>python app.py 2025-01-21 09:18:38 WARNING The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU cextension.py:96 quantization are unavailable.
> > So flyxgym is using cpu instead of gpu
> 
> No, I gave up. I'm not good enough with this Kode twerking to know how to fix it. I rent a 4090 on vast.ai instead. It's about 0,4 USD an hour and then you can use your pc for other tasks while it's running 😊

A ok :) and how does this works? you rent a gpu with a windows interface?

**Comment by goffy76** [comment]
> > > > I got i running like this: cd fluxgym && source env/bin/activate && export HSA_OVERRIDE_GFX_VERSION=11.0.0 && python3 app.py on my 7800XT, but it uses the CPU, not the GPU. Any ideas?
> > > 
> > > 
> > > Did you managed to make this work? I also have a 7800XT
> > > But when i am launching the app, i get this :
> > > (env) G:\A.I\fluxgym>python app.py 2025-01-21 09:18:38 WARNING The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU cextension.py:96 quantization are unavailable.
> > > So flyxgym is using cpu instead of gpu
> > 
> > 
> > No, I gave up. I'm not good enough with this Kode twerking to know how to fix it. I rent a 4090 on vast.ai instead. It's about 0,4 USD an hour and then you can use your pc for other tasks while it's running 😊
> 
> A ok :) and how does this works? you rent a gpu with a windows interface?

No, I run it in Yupyter. Follow the manuel install here https://github.com/cocktailpeanut/fluxgym

This video https://www.youtube.com/live/MJnPnS11IMk?si=E_Ml5hX-nNc3YLQ7 is also good.

Remember to edit the.   . Py file as he explain in the video 😊

**Comment by BradNagel** [comment]
Getting the same errors as OP. Sounds like AMD GPUs don't work. Suggest that a note be added to the main page that this is a Nvidia only application.

**Comment by hodfords** [comment]
With the upgrades to gradio and transformers - the following changes need to be made to requirements.txt as of Dec 2025; otherwise fluxgym would not work properly:-

transformers => transformers==4.49
gradio => gradio==5.50
