### ISSUE TITLE
after install Florence-2 not download

### ISSUE THREAD

**Issue by phenix14000** [cocktailpeanut/fluxgym#46]
hi,
After click on button "Add AI captionswith Florence-2"
in terminal have this:

A new version of the following files was downloaded from https://huggingface.co/multimodalart/Florence-2-large-no-flash-attn:
- modeling_florence2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
pytorch_model.bin:   0%| 

I can't add florence. I need uninstall & reistall fluxgym

**Comment by Jonseed** [comment]
It took a long time to download that `pytorch_model.bin` file for some reason. I just waited for it to finish the download.

**Comment by phenix14000** [comment]
> It took a long time to download that `pytorch_model.bin` file for some reason. I just waited for it to finish the download.

Thx, me not downloaded. 0% after 30 min. Where can i copy this file in folder of fluxgym?

**Comment by Jonseed** [comment]
You can download it [here](https://huggingface.co/multimodalart/Florence-2-large-no-flash-attn/blob/main/pytorch_model.bin), but I'm not sure where you are supposed to put it.

**Comment by sansbruhgaming** [comment]
> You can download it [here](https://huggingface.co/multimodalart/Florence-2-large-no-flash-attn/blob/main/pytorch_model.bin), but I'm not sure where you are supposed to put it.

Searching for the file in my own computer revealed this folder:
"%USERPROFILE%\.cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\snapshots\8db3793cf5b453b2ccfb3a4f613b403b2e6b7ca2"
Which hosts symlinks to files in another directory.
![image](https://github.com/user-attachments/assets/02ca5d03-0d8d-47cd-915f-ea1fcdb30dbd)

The symlinks point to:
"%USERPROFILE%\.cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\blobs"
With hashed names:
![image](https://github.com/user-attachments/assets/8d94e2c0-0c5a-40c8-8519-fd413f0b4fc8)

**Comment by phenix14000** [comment]
i've try to copy in cache but not work. I desinstall and i try install manually. Thx

**Comment by KLL535** [comment]
> i've try to copy in cache and work fine. Block in 0% after reinstall fluxgym, but after 5 min is downloaded. Thx

The problem is not solved

Write your exact path to the cache
My path C:\Users\AnY\.cache\huggingface\hub contains only one file
version_diffusers_cache.txt 
Inside it there is a number 1

There is a folder with the following files:
C:\Users\AnY\.cache\huggingface\modules\transformers_modules\multimodalart\Florence-2-large-no-flash-attn\8db3793cf5b453b2ccfb3a4f613b403b2e6b7ca2
__init__.py
configuration_florence2.py
modeling_florence2.py
__pycache__
   configuration_florence2.cpython-310.pyc
   modeling_florence2.cpython-310.pyc

I put a copy of pytorch_model.bin in every existing folder in the .cache and nothing helps!

Where is the cache!? The author is not interested in solving the artificially created problem (the file is successfully downloaded via the browser), which many have?

**Comment by KLL535** [comment]
I found it!!!

The location of the cache is controlled by this environment parameter:
set TRANSFORMERS_CACHE=%DIR%\transformers-cache
By default, FORGE placed it in its own folder.

You can change it to a folder in username:
set TRANSFORMERS_CACHE=C:\Users\username\ .cache\huggingface\hub

A file with a bunch of numbers will appear, you need to create a folder with this bunch of numbers and put it there model:
C:\Users\username\ .cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\blobs\a8b6ee6144f20a57200a0e3fab21f067d6cc77036262b72d9f6f7f4e556c8f15\pytorch_model.bin

After this, the file download does not occur! Progress!
 
But another problem arises. Which I do not know how to solve.

**...
 File "C:\webui_forge_cu121_torch21\webui\extensions\fluxgym\venv\lib\site-packages\huggingface_hub\file_download.py", line 946, in _create_symlink
    shutil.copyfile(abs_src, abs_dst)
  File "shutil.py", line 254, in copyfile
**PermissionError: [Errno 13] Permission denied:** 'C:\\Users\\username\\ .cache\\huggingface\\hub\\models--multimodalart--Florence-2-large-no-flash-attn\\blobs\\a8b6ee6144f20a57200a0e3fab21f067d6cc77036262b72d9f6f7f4e556c8f15'**

Moving the cache folder does not help. Administrator rights do not help. How this torments me.

**Comment by KLL535** [comment]
Florence WORK!

You need to put it not in blob but in snapshots.

My environment:

set TRANSFORMERS_CACHE=C:\Users\username\ .cache\huggingface\hub

My path:

C:\Users\username\ .cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\snapshots\8db3793cf5b453b2ccfb3a4f613b403b2e6b7ca2\pytorch_model.bin

**Comment by LeonLiu2020** [comment]
> Florence WORK!
> 
> You need to put it not in blob but in snapshots.
> 
> My environment:
> 
> set TRANSFORMERS_CACHE=C:\Users\username\ .cache\huggingface\hub
> 
> My path:
> 
> C:\Users\username\ .cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\snapshots\8db3793cf5b453b2ccfb3a4f613b403b2e6b7ca2\pytorch_model.bin

it doesnt work for me

**Comment by KLL535** [comment]
> > Florence WORK!
> > You need to put it not in blob but in snapshots.
> > My environment:
> > set TRANSFORMERS_CACHE=C:\Users\username\ .cache\huggingface\hub
> > My path:
> > C:\Users\username\ .cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\snapshots\8db3793cf5b453b2ccfb3a4f613b403b2e6b7ca2\pytorch_model.bin
> 
> it doesnt work for me

Write more details. You can't find the cache path? You put a file there, but the download still starts? Try to see how your environments are configured for this application, such as TRANSFORMERS_CACHE or HF_HOME (new format). What is written in PATH.

It's been a long time. I thought the download freezing problem was fixed.

**Comment by LeonLiu2020** [comment]
> > > Florence WORK!
> > > You need to put it not in blob but in snapshots.
> > > My environment:
> > > set TRANSFORMERS_CACHE=C:\Users\username\ .cache\huggingface\hub
> > > My path:
> > > C:\Users\username\ .cache\huggingface\hub\models--multimodalart--Florence-2-large-no-flash-attn\snapshots\8db3793cf5b453b2ccfb3a4f613b403b2e6b7ca2\pytorch_model.bin
> > 
> > 
> > it doesnt work for me
> 
> Write more details. You can't find the cache path? You put a file there, but the download still starts? Try to see how your environments are configured for this application, such as TRANSFORMERS_CACHE or HF_HOME (new format). What is written in PATH.
> 
> It's been a long time. I thought the download freezing problem was fixed.

Thank you for your response! I've found a way to resolve all the issues.

Since this library hasn’t been updated for a while, I had to modify some parts of the code, but fortunately, it was quite simple. For example:

In models.yaml, I changed flux1-dev.sft to flux1-dev.safetensors.
In app.py (starting from line 270), I updated the paths for Florence-2 and flux1.dev to local paths.
Similarly, I replaced ae.sft with ae.safetensors.
Additionally, sd-scripts requires t5-v1_1-xxl and clip-vit-large-patch14, so I downloaded them locally and updated the paths in the Python files.

This perfectly solved my problem. Thanks again!
