### ISSUE TITLE
ModuleNotFoundError: No module named 'slugify'

### ISSUE THREAD

**Issue by LineKernel** [cocktailpeanut/fluxgym#60]
hi
i get :
File "D:\AI\Lora Training Flux\fluxgym\app.py", line 16, in <module>
    from slugify import slugify
ModuleNotFoundError: No module named 'slugify'

when i try : python app.py
2 things i think it could be related to 
i dont know if : env/Scripts/activate worked i did it admin because other wise i get an error 
and i didnt update torch i m affraid to break all my other installs , so i didnt do this line :
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
is it necessary ? does my error come form this ?
thanks

**Comment by AndyLeAI** [comment]
reinstall modules from pip install -r requirements.txt to fix your issues !

**Comment by RalFingerLP** [comment]
You need start venv before you you run python app.py:
Windows: python -m venv env
env\Scripts\activate
Linux: python -m venv env
source env/bin/activate

**Comment by LineKernel** [comment]
> reinstall modules from pip install -r requirements.txt to fix your issues !

i did it with administrator privileges just in case and it worked ! 
Thank you very much
