### ISSUE TITLE
run app on 0.0.0.0 instead of 127.0.0.1?

### ISSUE THREAD

**Issue by fahadshery** [cocktailpeanut/fluxgym#80]
Hi,

I am trying to dockerise this application. is it possible to change the URL:  http://127.0.0.1:7860 to URL:  http://0.0.0.0:7860?

in that case, it would be super easy to manage it using reverse proxy
thanks

**Comment by fahadshery** [comment]
I think you can specify your own IP using the `server_name` args

See here: https://github.com/gradio-app/gradio/issues/260#issuecomment-900578935

how do I set it in your `app.py`?

**Comment by fahadshery** [comment]
Fixed it by updating the `app.py`:
```
if __name__ == "__main__":
    cwd = os.path.dirname(os.path.abspath(__file__))
    demo.launch(show_error=True, allowed_paths=[cwd],server_name="0.0.0.0")
```
it would be great if server ip is set via `args`
I have dockerised the app and will send a PR. 

Thank you for this amazing project!

**Comment by hamster-poodle** [comment]
Hi! Thx for contribution to run Fluxgym on cloudgpu. I really need a tutorial!

**Comment by fahadshery** [comment]
> this is a standard gradio interface, you can specify the listen address and port with environment variables :
> 
> ```
> export GRADIO_SERVER_NAME="0.0.0.0"
> 
> export GRADIO_SERVER_PORT=9000
> ```

thanks, I have updated the PR
