### ISSUE TITLE
ModuleNotFoundError: No module named 'train_network'

### ISSUE THREAD

**Issue by keizured** [cocktailpeanut/fluxgym#94]
When running `python app.py` after completing manual install steps this error shows. No clue how to resolve, any help would be appreciated

`ModuleNotFoundError: No module named 'train_network'`

**Comment by scooper86** [comment]
Same issue for me, installed via git on windows

**Comment by wuliang19869312** [comment]
Traceback (most recent call last):
  File "D:\fluxgym\app.py", line 17, in <module>
    import train_network
ModuleNotFoundError: No module named 'train_network'
why???

**Comment by one-pip** [comment]
yes, i git pull today , then met this problem

**Comment by vizuelvfx** [comment]
Wow, thank you!!! that helped me, I didn't know what to do either.

**Comment by one-pip** [comment]
> sys.path.append(os.path.abspath('./sd-scripts'))
> import train_network

can you teach me how to make it work?
sys.path.append(os.path.abspath('./sd-scripts'))
import train_network

**Comment by one-pip** [comment]
> I'm sure there's better way to do this, but here.
> 
> ```
> sys.path.append(os.path.abspath('./sd-scripts'))
> import train_network
> ```

thanks, i made it

**Comment by chnisar515** [comment]
i am facing the same error

> (env) E:\fluxgym>python app.py
Traceback (most recent call last):
  File "E:\fluxgym\app.py", line 17, in <module>
    import train_network
ModuleNotFoundError: No module named 'train_network'

can someone tell me how i can fix this?
i replaced these lines in my app.py file
now my app.py files looks like below

> import os
import sys
import subprocess
import gradio as gr
from PIL import Image
import torch
import uuid
import shutil
import json
import yaml
from slugify import slugify
from transformers import AutoProcessor, AutoModelForCausalLM
from gradio_logsview import LogsView, LogsViewRunner
from huggingface_hub import hf_hub_download, HfApi
from library import flux_train_utils, huggingface_util
from argparse import Namespace
import train_network
import toml
import re
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
os.environ['GRADIO_ANALYTICS_ENABLED'] = '0'
sys.path.insert(0, os.getcwd())
sys.path.append(os.path.abspath('./sd-scripts'))
import train_network
MAX_IMAGES = 150

**Comment by keizured** [comment]
Issue was resolved with latest commit, thank you for fix!
