### ISSUE TITLE
Wait for the author to update it, it doesn't work after yesterday's modification.

### ISSUE THREAD

**Issue by wuliang19869312** [cocktailpeanut/fluxgym#97]
Traceback (most recent call last):
  File "D:\fluxgym\app.py", line 17, in <module>
    import train_network
ModuleNotFoundError: No module named 'train_network'

**Comment by Tablaski** [comment]
I've had the same issue. I've solved it by copying fluxgym\sd-scripts\training_network.py into the root folder fluxgym
